default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual, pre-push]

exclude: "(^.*tests/.*$)"

repos:

# conventional commits

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
