name: Test with Docker Server

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      java_aas_server:
        image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
        ports:
          - 8075:5060
        env:
          SERVER_PORT: 5060
          SERVER_HOST: javaaasserver       
        options: >-
          --health-cmd="curl --fail http://localhost:8075/health || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for server to be healthy
        run: |
          echo "Waiting for server..."
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/health > /dev/null; then
              echo "Server is ready!"
              break
            fi
            sleep 2
          done

      - name: Run tests
        env:
          SERVER_URL: http://localhost:8080
        run: pytest -v
